# The default 80 character limit is sometimes unproductive
LineLength:
  Max: 120

# The default 10 lines limit is unrealistic
MethodLength:
  Max: 15

# Ignoring vendored gems
AllCops:
  Exclude:
    - 'vendor/*'

# Adding frozen_string_literal: false to every ruby file
# is annoying; will be re-visiting when Ruby 3.0 releases.
Style/FrozenStringLiteralComment:
  Enabled: false
