version: 2

jobs:
  build:
    docker:
       - image: circleci/ruby:2.4.1-node-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "Gemfile.lock" }}
          - v1-dependencies-
      - run:
          name: Install Dependencies
          command: |
            bundle install --jobs=4 --retry=3 --path vendor
      - save_cache:
          paths:
            - ./vendor
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}
      - run:
          name: Build Pages
          command: |
            bundle exec middleman build
  deploy:
    docker:
        - image: circleci/ruby:2.4.1-node-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Setup GitHub Pages Remote
          command: |
            git remote --verbose add gojektech-github-io ${GITHUB_PAGES_REPO}
      - run:
          name: Install Dependencies
          command: |
            bundle install --jobs=4 --retry=3 --path vendor
      - add_ssh_keys:
          fingerprints:
            - ""
      - run:
          name: Run Setup Script
          command: bash .circleci/setup.sh
      - run:
          name: Publish Master to GitHub Pages
          command: |
            bundle exec rake publish REMOTE_NAME=gojektech-github-io BRANCH_NAME=master

workflows:
  version: 2
  publish:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
